import{getFX,getGold,getQuote,refreshMarket}from'./market-data.js';
const DB='hesap-defteri-final',VER=2,STORES=['transactions','recurring','budgets','investments','sales','dividends','goals','prices','settings','fx'];
const S={db:null,tab:'home',month:mk(new Date()),settings:{baseCurrency:'TRY'}};
const INCOME=['Maaş','Kira Geliri','Serbest/Freelance Gelir','Hediye/Bağış','Vergi İadesi','Borç Tahsilatı','Diğer Gelir'];
const EXPENSE=['Market','Ulaşım','Kira','Faturalar','Restoran/Kafe','Abonelikler','Sigorta','Seyahat/Tatil','Evcil Hayvan','Spor/Fitness','Bağış/Hayır İşleri','Vergi/Resmi Ödemeler','Verilen Borç','Sağlık','Giyim','Eğitim','Diğer Gider'];
const METHODS=['Banka','Kredi Kartı','Banka Kartı','Nakit','Otomatik Ödeme','Diğer'], ASSETS=['BIST Hisse','BIST Fon','Yabancı Hisse','Altın','Döviz','Diğer'];
const COLORS=['#16302B','#B98900','#A63D2F','#1E6B4E','#3E5850','#8A6D3B','#6C5B7B','#4B7F8C'];
function mk(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}function prev(k){const d=new Date(k+'-01');d.setMonth(d.getMonth()-1);return mk(d)}function next(k){const d=new Date(k+'-01');d.setMonth(d.getMonth()+1);return mk(d)}function uid(){return crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`}function today(){return new Date().toISOString().slice(0,10)}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function num(x){const n=Number(x);return Number.isFinite(n)?n:0}function money(x,c='TRY'){try{return new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,maximumFractionDigits:2}).format(num(x))}catch{return `${fmt(x)} ${c}`}}function fmt(x){return new Intl.NumberFormat('tr-TR',{maximumFractionDigits:2}).format(num(x))}function mname(k){const[y,m]=k.split('-').map(Number);return new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'}).format(new Date(y,m-1,1))}
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;STORES.forEach(s=>{if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:'id'})})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function all(s){return new Promise((ok,no)=>{const q=S.db.transaction(s,'readonly').objectStore(s).getAll();q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)})}function put(s,o){return new Promise((ok,no)=>{const q=S.db.transaction(s,'readwrite').objectStore(s).put(o);q.onsuccess=()=>ok(o);q.onerror=()=>no(q.error)})}function del(s,id){return new Promise((ok,no)=>{const q=S.db.transaction(s,'readwrite').objectStore(s).delete(id);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)})}
async function set(k,v){const a=await all('settings'),old=a.find(x=>x.key===k);return put('settings',{id:old?.id||uid(),key:k,value:v})}async function get(k,d){return(await all('settings')).find(x=>x.key===k)?.value??d}
async function ratesFor(date){const key=`${date}|TRY`;const cached=(await all('fx')).find(x=>x.key===key);if(cached&&num(cached.rates?.EUR)>0&&num(cached.rates?.USD)>0)return cached.rates;try{const j=await getFX('TRY',['EUR','USD'],date);const r={TRY:1,EUR:num(j.rates.EUR),USD:num(j.rates.USD)};if(r.EUR>0&&r.USD>0){await put('fx',{id:key,key,rates:r,date,sourceDate:j.date});return r}}catch(_){}try{const j=await getFX('TRY',['EUR','USD']);const r={TRY:1,EUR:num(j.rates.EUR),USD:num(j.rates.USD)};if(r.EUR>0&&r.USD>0){await put('fx',{id:key,key,rates:r,date,sourceDate:j.date,latestFallback:true});return r}}catch(_){}return cached?.rates||{TRY:1,EUR:0,USD:0}}
async function snapshotFor(currency,date){const r=await ratesFor(date);if(currency==='TRY')return r;const x=num(r[currency]);if(!x)return{TRY:1,EUR:1,USD:1};return{TRY:1/x,EUR:currency==='EUR'?1:num(r.EUR)/x,USD:currency==='USD'?1:num(r.USD)/x}}
async function toBase(t){if(t.currency===S.settings.baseCurrency)return num(t.amount);const snap=t.fxSnapshot||await snapshotFor(t.currency,t.date);return num(t.amount)*num(snap[S.settings.baseCurrency]||0)}
async function saveTx(data,existing){const date=data.date||today();const o={...existing,...data,id:existing?.id||uid(),date,month:date.slice(0,7),amount:num(data.amount),fxSnapshot:data.fxSnapshot||await snapshotFor(data.currency,date),createdAt:existing?.createdAt||new Date().toISOString()};await put('transactions',o);return o}
async function ensureRecurring(){const rec=(await all('recurring')).filter(x=>x.active),tx=await all('transactions');for(const r of rec){for(let i=-2;i<=1;i++){const d=new Date(S.month+'-01');d.setMonth(d.getMonth()+i);const m=mk(d),days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),day=Math.min(num(r.day)||1,days);if(!tx.some(t=>t.recurringId===r.id&&t.month===m)){const date=`${m}-${String(day).padStart(2,'0')}`;await saveTx({recurringId:r.id,type:'expense',date,category:r.category,description:r.description,paymentMethod:r.paymentMethod,currency:r.currency,amount:r.amount})}}}}
async function month(k){const tx=(await all('transactions')).filter(x=>x.month===k);let income=0,expense=0;const cat={};for(const t of tx){const v=await toBase(t);if(t.type==='income')income+=v;else{expense+=v;cat[t.category]=(cat[t.category]||0)+v}}return{tx,income,expense,net:income-expense,cat}}
async function carry(k){let total=0,d=new Date(k+'-01');for(let i=0;i<240;i++){d.setMonth(d.getMonth()-1);const m=await month(mk(d));total+=m.net}return total}
function donut(parts){const total=parts.reduce((a,x)=>a+x.v,0)||1;let a=0,st=[];for(const p of parts){const b=a+p.v;st.push(`${p.color} ${a/total*360}deg ${b/total*360}deg`);a=b}return`<div class="donut" style="background:conic-gradient(${st.join(',')})"></div>`}
function bar(prevIncome,prevExpense,curIncome,curExpense){const max=Math.max(prevIncome,prevExpense,curIncome,curExpense,1),w=360,h=170,base=132,scale=86/max;const bh=v=>Math.max(3,v*scale),y=v=>base-bh(v);return`<div><div style="display:flex;gap:14px;align-items:center;margin:0 0 8px;font-size:11px;color:var(--ink-soft)"><span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:#23785A;margin-right:5px"></i>Gelir</span><span><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:#B54839;margin-right:5px"></i>Gider</span></div><svg class="chart" viewBox="0 0 ${w} ${h}"><rect x="62" y="${y(prevIncome)}" width="45" height="${bh(prevIncome)}" rx="8" fill="#23785A"/><rect x="113" y="${y(prevExpense)}" width="45" height="${bh(prevExpense)}" rx="8" fill="#B54839"/><rect x="203" y="${y(curIncome)}" width="45" height="${bh(curIncome)}" rx="8" fill="#23785A"/><rect x="254" y="${y(curExpense)}" width="45" height="${bh(curExpense)}" rx="8" fill="#B54839"/><text x="110" y="156" text-anchor="middle" font-size="11" font-weight="600" fill="#4B625B">Geçen Ay</text><text x="251" y="156" text-anchor="middle" font-size="11" font-weight="600" fill="#4B625B">Bu Ay</text><text x="84" y="${Math.max(14,y(prevIncome)-6)}" text-anchor="middle" font-size="9" fill="#4B625B">${money(prevIncome,S.settings.baseCurrency)}</text><text x="135" y="${Math.max(14,y(prevExpense)-6)}" text-anchor="middle" font-size="9" fill="#4B625B">${money(prevExpense,S.settings.baseCurrency)}</text><text x="225" y="${Math.max(14,y(curIncome)-6)}" text-anchor="middle" font-size="9" fill="#4B625B">${money(curIncome,S.settings.baseCurrency)}</text><text x="276" y="${Math.max(14,y(curExpense)-6)}" text-anchor="middle" font-size="9" fill="#4B625B">${money(curExpense,S.settings.baseCurrency)}</text></svg></div>`}
async function budgetToBase(b){if(b.currency===S.settings.baseCurrency)return num(b.limit);const r=await ratesFor(today());return convertCurrent(num(b.limit),b.currency,S.settings.baseCurrency,r)}
async function home(){const m=await month(S.month),p=await month(prev(S.month)),cv=await carry(S.month),base=S.settings.baseCurrency,parts=Object.entries(m.cat).map(([label,v],i)=>({label,v,color:COLORS[i%COLORS.length]})).sort((a,b)=>b.v-a.v).slice(0,8),bud=(await all('budgets')).filter(x=>x.month===S.month);let budgetHtml='';if(bud.length){const out=[];for(const b of bud){const spent=m.cat[b.category]||0,limitBase=await budgetToBase(b),pct=limitBase?spent/limitBase*100:0;out.push(`<div class="list-item"><div class="row"><b>${esc(b.category)}</b><span class="${pct>100?'negative':''}">${money(spent,base)} / ${money(limitBase,base)}</span></div><div class="progress"><i style="width:${Math.min(100,pct)}%"></i></div>${pct>100?`<div class="tiny negative">Limit aşıldı · %${fmt(pct)}</div>`:''}</div>`)}budgetHtml=out.join('')}else budgetHtml='<div class="empty">Bütçe tanımlanmadı.</div>';return`<div class="card"><div class="monthbar"><button data-month="-1">‹</button><div class="right"><b>${mname(S.month)}</b><div class="muted">Ana para birimi: ${base}</div></div><button data-month="1">›</button></div></div><div class="grid2"><div class="card kpi"><div class="label">Gelir</div><div class="value positive">${money(m.income,base)}</div></div><div class="card kpi"><div class="label">Gider</div><div class="value negative">${money(m.expense,base)}</div></div></div><div class="card kpi"><div class="label">Ay neti</div><div class="value ${m.net>=0?'positive':'negative'}">${money(m.net,base)}</div><div class="muted">Önceki aylardan birikmiş devir: ${money(cv,base)}</div></div><div class="grid2"><button class="btn secondary" data-action="income">+ Gelir</button><button class="btn secondary" data-action="expense">− Gider</button></div><div class="section-head"><h2>Aylık Trend</h2></div><div class="card">${bar(p.income,p.expense,m.income,m.expense)}</div><div class="section-head"><h2>Kategori Dağılımı</h2></div><div class="card">${parts.length?`<div class="donut-wrap">${donut(parts)}<div class="legend">${parts.map(x=>`<span>${esc(x.label)} · ${money(x.v,base)}</span>`).join('')}</div></div>`:'<div class="empty">Bu ay gider yok.</div>'}</div><div class="section-head"><h2>Bütçe Uyarıları</h2><button class="btn small" data-action="budget">+ Limit</button></div><div class="card">${budgetHtml}</div>`}
function txForm(t,type){const x=t||{type:type||'expense',date:today(),category:(type==='income'?INCOME:EXPENSE)[0],paymentMethod:'Banka',currency:S.settings.baseCurrency,amount:'',description:''};const cats=x.type==='income'?INCOME:EXPENSE;return`<div class="form-grid"><div><label>Tür</label><select id="fType"><option value="expense" ${x.type==='expense'?'selected':''}>Gider</option><option value="income" ${x.type==='income'?'selected':''}>Gelir</option></select></div><div><label>Tarih</label><input id="fDate" type="date" value="${x.date}"></div><div><label>Kategori</label><select id="fCat">${cats.map(c=>`<option ${c===x.category?'selected':''}>${c}</option>`).join('')}</select></div><div><label>Ödeme yöntemi</label><select id="fMethod">${METHODS.map(c=>`<option ${c===x.paymentMethod?'selected':''}>${c}</option>`).join('')}</select></div><div><label>Tutar</label><input id="fAmount" type="number" step="0.01" min="0" value="${x.amount}"></div><div><label>Para birimi</label><select id="fCur">${['TRY','EUR','USD'].map(c=>`<option ${c===x.currency?'selected':''}>${c}</option>`).join('')}</select></div><div class="full"><label>Açıklama</label><input id="fDesc" value="${esc(x.description)}"></div></div><button class="btn" id="saveTx" style="width:100%;margin-top:10px">Kaydet</button>`}
async function openTx(t,type){
 modal(t?'Hareketi düzenle':'Yeni hareket',txForm(t,type));
 const typeEl=document.getElementById('fType'),catEl=document.getElementById('fCat'),methodEl=document.getElementById('fMethod'),amountEl=document.getElementById('fAmount'),dateEl=document.getElementById('fDate'),curEl=document.getElementById('fCur'),descEl=document.getElementById('fDesc'),saveBtn=document.getElementById('saveTx');
 const fillCats=()=>{const cats=typeEl.value==='income'?INCOME:EXPENSE;catEl.innerHTML=cats.map(c=>`<option>${esc(c)}</option>`).join('');if(t?.category&&cats.includes(t.category))catEl.value=t.category};
 typeEl.addEventListener('change',fillCats);fillCats();
 saveBtn.addEventListener('click',async()=>{try{const amount=num(amountEl.value);if(amount<=0)throw Error('Tutar 0’dan büyük olmalı.');if(!dateEl.value)throw Error('Tarih gerekli.');await saveTx({type:typeEl.value,date:dateEl.value,category:catEl.value,paymentMethod:methodEl.value,amount,currency:curEl.value,description:descEl.value.trim()},t);close();toast('Kayıt kaydedildi');await render()}catch(e){alert('Kayıt kaydedilemedi: '+e.message)}})
}
async function transactions(){const tx=(await all('transactions')).filter(x=>x.month===S.month).sort((a,b)=>b.date.localeCompare(a.date));const rec=(await all('recurring')).filter(x=>x.active);return`<div class="card"><div class="monthbar"><button data-month="-1">‹</button><b>${mname(S.month)}</b><button data-month="1">›</button></div><button class="btn" style="width:100%;margin-top:10px" data-action="newtx">+ Yeni hareket</button></div><div class="section-head"><h2>Hareketler</h2><span class="muted">${tx.length} kayıt</span></div><div class="card">${tx.length?tx.map(t=>`<div class="list-item"><div class="row"><div><b>${esc(t.description||t.category)}</b><div class="muted">${esc(t.category)} · ${t.date} · ${esc(t.paymentMethod)}</div></div><div class="right"><b class="${t.type==='income'?'income':'expense'}">${t.type==='income'?'+':'−'}${money(t.amount,t.currency)}</b><div class="actions"><button class="btn small secondary" data-edit="${t.id}">Düzenle</button><button class="btn small danger" data-del="${t.id}">Sil</button></div></div></div></div>`).join(''):'<div class="empty">Bu ay kayıt yok.</div>'}</div><div class="section-head"><h2>Tekrarlayan Giderler</h2><button class="btn small" data-action="recurring">+ Ekle</button></div><div class="card">${rec.length?rec.map(r=>`<div class="list-item row"><div><b>${esc(r.description)}</b><div class="muted">${esc(r.category)} · ayın ${r.day}. günü</div></div><b>${money(r.amount,r.currency)}</b></div>`).join(''):'<div class="empty">Tekrarlayan gider yok.</div>'}</div><div class="section-head"><h2>Aylık Bütçe</h2><button class="btn small" data-action="budget">+ Limit</button></div><div class="card"><div class="muted">Limitler Özet ekranında otomatik hesaplanır.</div></div><div class="section-head"><h2>Yedekleme</h2></div><div class="grid2"><button class="btn secondary" data-action="backup">Dışa aktar</button><button class="btn secondary" data-action="restore">Geri yükle</button></div>`}
async function currentRates(){try{return await ratesFor(today())}catch{return{TRY:1,EUR:0,USD:0}}}
function convertCurrent(amount,currency,base,r){if(currency===base)return num(amount);const toBase=num(r[base]),from=num(r[currency]);if(!from||!toBase)return 0;return num(amount)*toBase/from}
async function portfolio(){
 const inv=await all('investments'),sales=await all('sales'),divs=await all('dividends'),prices=await all('prices'),base=S.settings.baseCurrency,rates=await currentRates();
 const symbols=[...new Set(inv.map(x=>x.symbol))],rows=[];let totalValue=0,totalCost=0,totalDiv=0,totalReal=0;
 for(const sym of symbols){
  const buys=inv.filter(x=>x.symbol===sym),ss=sales.filter(x=>x.symbol===sym),ds=divs.filter(x=>x.symbol===sym),first=buys[0],type=first?.type||'Diğer',currency=first?.currency||'TRY';
  const boughtQty=buys.reduce((a,x)=>a+num(x.qty),0),soldQty=ss.reduce((a,x)=>a+num(x.qty),0),qty=Math.max(0,boughtQty-soldQty),cost=boughtQty?buys.reduce((a,x)=>a+num(x.qty)*num(x.buyPrice),0):0,avg=boughtQty?cost/boughtQty:0;
  let p=prices.find(x=>x.symbol===sym)?.price??0;
  if(type==='Döviz')p=1;
  const value=qty*p,realized=ss.reduce((a,x)=>a+num(x.realized),0),div=ds.filter(x=>x.currency===currency).reduce((a,x)=>a+num(x.amount),0),priceGain=value-qty*avg,totalReturn=priceGain+realized+div;
  const valueBase=convertCurrent(value,currency,base,rates),costBase=convertCurrent(qty*avg,currency,base,rates),realBase=convertCurrent(realized,currency,base,rates),divBase=convertCurrent(div,currency,base,rates);
  totalValue+=valueBase;totalCost+=costBase;totalReal+=realBase;totalDiv+=divBase;
  rows.push({symbol:sym,type,currency,qty,avg,p,value,realized,div,priceGain,totalReturn,valueBase,costBase,realBase,divBase,source:prices.find(x=>x.symbol===sym)?.source||(type==='Döviz'?'Güncel kur':'Fiyat yok')});
 }
 const unrealized=totalValue-totalCost,totalReturn=unrealized+totalReal+totalDiv;
 return`<div class="card"><div class="row"><div><div class="eyebrow">PORTFÖY</div><h2>${money(totalValue,base)}</h2></div><button class="btn gold" data-action="refresh">Fiyatları Güncelle</button></div><div class="muted">Maliyet ${money(totalCost,base)} · Gerçekleşmemiş ${money(unrealized,base)} · Gerçekleşmiş ${money(totalReal,base)} · Temettü ${money(totalDiv,base)}</div><div class="${totalReturn>=0?'positive':'negative'}" style="margin-top:5px">Toplam getiri: ${money(totalReturn,base)} · ${totalCost?fmt(totalReturn/totalCost*100):'0'}%</div><div class="tiny">Son güncelleme: ${esc(await get('marketUpdated','—'))}</div></div><div class="grid2"><button class="btn secondary" data-action="buy">+ Alış</button><button class="btn secondary" data-action="projection">Bileşik Getiri</button></div><div class="section-head"><h2>Varlıklar</h2></div><div class="card">${rows.length?rows.map(r=>`<div class="list-item"><div class="row"><div><b>${esc(r.symbol)}</b><div class="muted">${esc(r.type)} · ${fmt(r.qty)} adet · Ort. ${money(r.avg,r.currency)}</div><div class="tiny">${esc(r.source)}</div></div><div class="right"><b>${money(r.value,r.currency)}</b><div class="${r.priceGain>=0?'positive':'negative'}">Açık K/Z ${r.priceGain>=0?'+':''}${money(r.priceGain,r.currency)} · ${r.qty*r.avg?fmt(r.priceGain/(r.qty*r.avg)*100):'0'}%</div></div></div><div class="muted" style="margin-top:5px">Gerçekleşmiş ${money(r.realized,r.currency)} · Temettü ${money(r.div,r.currency)} · Toplam getiri ${money(r.totalReturn,r.currency)}</div><div class="actions" style="margin-top:7px"><button class="btn small secondary" data-sell="${esc(r.symbol)}">Satış</button><button class="btn small secondary" data-div="${esc(r.symbol)}">Temettü</button></div></div>`).join(''):'<div class="empty">Portföy boş.</div>'}</div><div class="section-head"><h2>Dağılım</h2></div><div class="card">${rows.length?(()=>{const p=rows.filter(x=>x.valueBase>0).map((x,i)=>({label:x.symbol,v:x.valueBase,color:COLORS[i%COLORS.length]}));return p.length?`<div class="donut-wrap">${donut(p)}<div class="legend">${p.map(x=>`<span>${esc(x.label)} · ${money(x.v,base)}</span>`).join('')}</div></div>`:'<div class="empty">Fiyat bulunamadı.</div>'})():'<div class="empty">Yatırım ekleyin.</div>'}</div><div id="projection"></div>`
}
async function buyForm(){
 modal('Yatırım alış',`<div class="form-grid"><div><label>Tür</label><select id="iType">${ASSETS.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div><label>Sembol</label><input id="iSym" placeholder="EREGL / AAPL"></div><div><label>Adet / Lot / Gram</label><input id="iQty" type="number" min="0" step="0.0001"></div><div><label>Alış fiyatı / Kur</label><input id="iPrice" type="number" min="0" step="0.0001"></div><div><label>Para birimi</label><select id="iCur"><option>TRY</option><option>USD</option><option>EUR</option></select></div><div><label>Tarih</label><input id="iDate" type="date" value="${today()}"></div><div class="full"><label>İsim</label><input id="iName"></div></div><button class="btn" id="iSave" style="width:100%;margin-top:10px">Kaydet</button>`);
 const typeEl=document.getElementById('iType'),symEl=document.getElementById('iSym'),qtyEl=document.getElementById('iQty'),priceEl=document.getElementById('iPrice'),curEl=document.getElementById('iCur'),dateEl=document.getElementById('iDate'),nameEl=document.getElementById('iName'),saveBtn=document.getElementById('iSave');
 const sync=()=>{const special=typeEl.value==='Altın'||typeEl.value==='Döviz';symEl.disabled=special;symEl.placeholder=typeEl.value==='Altın'?'Sembol gerekmez':typeEl.value==='Döviz'?'EUR / USD':'EREGL / AAPL';if(typeEl.value==='Altın'){symEl.value='GRAM_ALTIN';curEl.value='TRY'}else if(typeEl.value==='Döviz'){symEl.value=curEl.value;nameEl.value=curEl.value}else if(symEl.value==='GRAM_ALTIN')symEl.value='';};
 typeEl.addEventListener('change',sync);curEl.addEventListener('change',()=>{if(typeEl.value==='Döviz'){symEl.value=curEl.value;nameEl.value=curEl.value}});sync();
 saveBtn.addEventListener('click',async()=>{try{const type=typeEl.value,q=num(qtyEl.value),p=num(priceEl.value),date=dateEl.value;let sym=symEl.value.trim().toUpperCase();if(type==='Altın')sym='GRAM_ALTIN';if(type==='Döviz')sym=curEl.value;if(q<=0||p<=0)throw Error('Miktar ve fiyat 0’dan büyük olmalı.');if(!sym)throw Error('Sembol gerekli.');if(!date)throw Error('Tarih gerekli.');await put('investments',{id:uid(),type,symbol:sym,name:nameEl.value.trim()||sym,qty:q,buyPrice:p,currency:curEl.value,date});close();await render();toast('Yatırım kaydedildi')}catch(e){alert('Yatırım kaydedilemedi: '+e.message)}})
}
async function sellForm(sym){
 const buys=(await all('investments')).filter(x=>x.symbol===sym),ss=(await all('sales')).filter(x=>x.symbol===sym),bq=buys.reduce((a,x)=>a+num(x.qty),0),sq=ss.reduce((a,x)=>a+num(x.qty),0),qty=bq-sq,avg=bq?buys.reduce((a,x)=>a+num(x.qty)*num(x.buyPrice),0)/bq:0;
 if(qty<=0)return alert('Satılabilir miktar yok.');
 modal('Satış',`<div class="notice">${esc(sym)} · Kullanılabilir: ${fmt(qty)} · Ağırlıklı ortalama maliyet: ${fmt(avg)}</div><div class="form-grid"><div><label>Adet / Gram</label><input id="sQty" type="number" min="0" max="${qty}" step="0.0001"></div><div><label>Satış fiyatı / Kur</label><input id="sPrice" type="number" min="0" step="0.0001"></div><div><label>Para birimi</label><input id="sCur" value="${buys[0]?.currency||'TRY'}" readonly></div><div><label>Tarih</label><input id="sDate" type="date" value="${today()}"></div></div><button class="btn" id="sSave" style="width:100%;margin-top:10px">Satışı kaydet</button>`);
 const qtyEl=document.getElementById('sQty'),priceEl=document.getElementById('sPrice'),curEl=document.getElementById('sCur'),dateEl=document.getElementById('sDate'),saveBtn=document.getElementById('sSave');
 saveBtn.addEventListener('click',async()=>{try{const q=num(qtyEl.value),p=num(priceEl.value);if(q<=0||q>qty)throw Error('Satış adedini kontrol edin.');if(p<=0)throw Error('Satış fiyatı 0’dan büyük olmalı.');await put('sales',{id:uid(),symbol:sym,qty:q,sellPrice:p,costPerUnit:avg,realized:(p-avg)*q,currency:curEl.value,date:dateEl.value});close();await render();toast('Satış kaydedildi')}catch(e){alert('Satış kaydedilemedi: '+e.message)}})
}
async function divForm(sym){
 const inv=(await all('investments')).find(x=>x.symbol===sym);modal('Temettü',`<div class="form-grid"><div><label>Tutar</label><input id="dAmt" type="number" min="0" step="0.01"></div><div><label>Para birimi</label><input id="dCur" value="${inv?.currency||'TRY'}" readonly></div><div><label>Tarih</label><input id="dDate" type="date" value="${today()}"></div></div><button class="btn" id="dSave" style="width:100%;margin-top:10px">Kaydet</button>`);
 const amtEl=document.getElementById('dAmt'),saveBtn=document.getElementById('dSave');saveBtn.addEventListener('click',async()=>{try{const amount=num(amtEl.value);if(amount<=0)throw Error('Temettü tutarı 0’dan büyük olmalı.');await put('dividends',{id:uid(),symbol:sym,amount,currency:document.getElementById('dCur').value,date:document.getElementById('dDate').value});close();await render();toast('Temettü kaydedildi')}catch(e){alert('Temettü kaydedilemedi: '+e.message)}})
}
async function recurringForm(){
 modal('Tekrarlayan gider',`<div class="form-grid"><div><label>Kategori</label><select id="rCat">${EXPENSE.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div><label>Gün</label><input id="rDay" type="number" min="1" max="31" value="1"></div><div><label>Tutar</label><input id="rAmt" type="number" min="0" step="0.01"></div><div><label>Para birimi</label><select id="rCur"><option>TRY</option><option>EUR</option><option>USD</option></select></div><div class="full"><label>Açıklama</label><input id="rDesc"></div><div class="full"><label>Ödeme</label><select id="rMethod">${METHODS.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div></div><button class="btn" id="rSave" style="width:100%;margin-top:10px">Kaydet</button>`);
 const amtEl=document.getElementById('rAmt'),saveBtn=document.getElementById('rSave');saveBtn.addEventListener('click',async()=>{try{if(num(amtEl.value)<=0)throw Error('Tutarı girin.');await put('recurring',{id:uid(),day:Math.min(31,Math.max(1,Math.floor(num(document.getElementById('rDay').value)))),amount:num(amtEl.value),currency:document.getElementById('rCur').value,category:document.getElementById('rCat').value,description:document.getElementById('rDesc').value.trim(),paymentMethod:document.getElementById('rMethod').value,active:true});close();await render();toast('Tekrarlayan gider kaydedildi')}catch(e){alert('Kayıt kaydedilemedi: '+e.message)}})
}
async function budgetForm(){
 modal('Aylık bütçe',`<div class="form-grid"><div><label>Kategori</label><select id="bCat">${EXPENSE.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div><label>Limit (${S.settings.baseCurrency})</label><input id="bLimit" type="number" min="0" step="0.01"></div></div><button class="btn" id="bSave" style="width:100%;margin-top:10px">Kaydet</button>`);
 const catEl=document.getElementById('bCat'),limitEl=document.getElementById('bLimit'),saveBtn=document.getElementById('bSave');saveBtn.addEventListener('click',async()=>{try{const limit=num(limitEl.value);if(limit<=0)throw Error('Limit girin.');const old=(await all('budgets')).find(x=>x.month===S.month&&x.category===catEl.value);await put('budgets',{id:old?.id||uid(),month:S.month,category:catEl.value,limit,currency:S.settings.baseCurrency});close();await render();toast('Bütçe kaydedildi')}catch(e){alert('Bütçe kaydedilemedi: '+e.message)}})
}
async function projection(){const p=document.getElementById('projection');if(!p)return;p.innerHTML=`<div class="section-head"><h2>Bileşik Getiri</h2></div><div class="card"><div class="form-grid"><div><label>Başlangıç</label><input id="qStart" type="number" min="0" value="0"></div><div><label>Aylık katkı</label><input id="qMonthly" type="number" min="0" value="10000"></div><div><label>Yıllık getiri %</label><input id="qRate" type="number" value="10"></div><div><label>Süre (yıl)</label><input id="qYears" type="number" min="0" step="0.1" value="10"></div></div><div class="grid2" style="margin-top:10px"><button class="btn" id="qMonthlyMode">Aylık katkı</button><button class="btn secondary" id="qOneMode">Tek sefer</button></div><div id="qOut" class="card"></div></div>`;let mode='monthly';const startEl=document.getElementById('qStart'),monthlyEl=document.getElementById('qMonthly'),rateEl=document.getElementById('qRate'),yearsEl=document.getElementById('qYears'),outEl=document.getElementById('qOut'),monthlyBtn=document.getElementById('qMonthlyMode'),oneBtn=document.getElementById('qOneMode');const calc=()=>{const start=num(startEl.value),m=num(monthlyEl.value),r=num(rateEl.value)/100,y=Math.max(0,num(yearsEl.value)),n=Math.round(y*12);if(r<=-1){outEl.textContent='Getiri oranı -%100 veya daha düşük olamaz.';return}const rm=Math.pow(1+r,1/12)-1;let fv=start*Math.pow(1+rm,n);if(mode==='monthly'){for(let i=0;i<n;i++)fv+=m*Math.pow(1+rm,n-1-i)}const invested=start+(mode==='monthly'?m*n:0),gain=fv-invested,doubling=r>0?Math.log(2)/Math.log(1+r):Infinity;outEl.innerHTML=`<b>Gelecek değer: ${money(fv,S.settings.baseCurrency)}</b><div class="muted">Yatırılan: ${money(invested,S.settings.baseCurrency)} · Tahmini getiri: ${money(gain,S.settings.baseCurrency)}${Number.isFinite(doubling)?` · 2× yaklaşık ${doubling.toFixed(1)} yıl`:''}</div>`};monthlyBtn.addEventListener('click',()=>{mode='monthly';monthlyBtn.className='btn';oneBtn.className='btn secondary';calc()});oneBtn.addEventListener('click',()=>{mode='one';oneBtn.className='btn';monthlyBtn.className='btn secondary';calc()});[startEl,monthlyEl,rateEl,yearsEl].forEach(el=>el.addEventListener('input',calc));calc()}

async function goals(){const gs=await all('goals');return`<div class="section-head"><h2>Birikim Hedefleri</h2><button class="btn small" data-action="goal">+ Hedef</button></div>${gs.length?gs.map(g=>{const pct=g.target?Math.min(100,g.current/g.target*100):0,remaining=Math.max(0,num(g.target)-num(g.current)),days=g.date?Math.max(0,Math.ceil((new Date(g.date+'T23:59:59')-new Date())/86400000)):null,months=days==null?null:Math.max(days/30.4375,1),monthly=months?remaining/months:0;return`<div class="card"><div class="row"><div><h3>${esc(g.name)}</h3><div class="muted">Hedef: ${esc(g.date||'Tarihsiz')}</div></div><b>${fmt(pct)}%</b></div><div class="progress" style="margin:10px 0"><i style="width:${pct}%"></i></div><div class="row"><span>${money(g.current,g.currency)}</span><span>${money(g.target,g.currency)}</span></div><div class="grid2" style="margin-top:10px"><div><div class="tiny">Kalan</div><b>${money(remaining,g.currency)}</b></div><div><div class="tiny">Kalan gün</div><b>${days==null?'—':days}</b></div></div>${months?`<div class="notice" style="margin-top:10px">Gerekli yaklaşık aylık birikim: <b>${money(monthly,g.currency)}</b></div>`:''}<div class="actions" style="margin-top:8px"><button class="btn small secondary" data-goaladd="${g.id}">İlerleme</button><button class="btn small danger" data-goaldel="${g.id}">Sil</button></div></div>`}).join(''):'<div class="card empty">Henüz hedef yok.</div>'}`}
async function goalForm(){
 modal('Birikim hedefi',`<div class="form-grid"><div class="full"><label>Ad</label><input id="gName"></div><div><label>Hedef</label><input id="gTarget" type="number" min="0"></div><div><label>Mevcut</label><input id="gCurrent" type="number" min="0" value="0"></div><div><label>Para birimi</label><select id="gCur"><option>TRY</option><option>EUR</option><option>USD</option></select></div><div><label>Hedef tarihi</label><input id="gDate" type="date"></div></div><button class="btn" id="gSave" style="width:100%;margin-top:10px">Kaydet</button>`);
 const nameEl=document.getElementById('gName'),targetEl=document.getElementById('gTarget'),saveBtn=document.getElementById('gSave');saveBtn.addEventListener('click',async()=>{try{if(!nameEl.value.trim()||num(targetEl.value)<=0)throw Error('Hedef adı ve tutar gerekli.');await put('goals',{id:uid(),name:nameEl.value.trim(),target:num(targetEl.value),current:num(document.getElementById('gCurrent').value),currency:document.getElementById('gCur').value,date:document.getElementById('gDate').value});close();await render();toast('Hedef kaydedildi')}catch(e){alert('Hedef kaydedilemedi: '+e.message)}})
}
async function backup(){const data={schema:2,createdAt:new Date().toISOString(),stores:{}};for(const s of STORES)data.stores[s]=await all(s);const blob=new Blob([JSON.stringify(data)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`hesap-defteri-yedek-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function restore(){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const d=JSON.parse(await i.files[0].text());if(!d.stores)throw Error('Geçersiz yedek');if(!confirm('Mevcut veriler yedekten tamamen değiştirilsin mi?'))return;for(const s of STORES)for(const x of await all(s))await del(s,x.id);for(const s of STORES)for(const x of d.stores[s]||[])await put(s,x);toast('Yedek geri yüklendi');await render()}catch(e){alert('Yedek geri yüklenemedi: '+e.message)}};i.click()}
async function refresh(){toast('Piyasa verileri güncelleniyor…');const inv=await all('investments'),syms=[...new Set(inv.filter(x=>x.type!=='Altın'&&x.type!=='Döviz').map(x=>x.symbol))],r=await refreshMarket(syms);if(r.fx){const rates={TRY:1,EUR:num(r.fx.rates.EUR),USD:num(r.fx.rates.USD)};await put('fx',{id:`${today()}|TRY`,key:`${today()}|TRY`,date:today(),rates})}if(r.gold){await put('prices',{id:r.gold.symbol,symbol:r.gold.symbol,price:r.gold.sell,currency:r.gold.currency,source:r.gold.source,updatedAt:r.gold.updatedAt,meta:r.gold})}for(const q of r.quotes)await put('prices',{id:q.symbol,symbol:q.symbol,price:q.price,currency:q.currency,source:q.source,updatedAt:q.updatedAt});await set('marketUpdated',new Date().toLocaleString('tr-TR'));toast(r.errors.length?`Güncellendi · ${r.errors.length} kaynak uyarısı`:'Piyasalar güncellendi');render()}
async function settings(){modal('Ayarlar',`<label>Ana para birimi<select id="base">${['TRY','EUR','USD'].map(x=>`<option ${x===S.settings.baseCurrency?'selected':''}>${x}</option>`).join('')}</select></label><div class="notice" style="margin-top:10px">Veriler cihazda IndexedDB'de tutulur. Piyasa verisi internet yoksa son kayıtlı fiyat/kurlar kullanılır.</div><button class="btn" id="saveSet" style="width:100%;margin-top:10px">Kaydet</button><button class="btn secondary" id="clear" style="width:100%;margin-top:8px">Tüm verileri sil</button>`);const baseEl=document.getElementById('base'),saveBtn=document.getElementById('saveSet'),clearBtn=document.getElementById('clear');saveBtn.addEventListener('click',async()=>{S.settings.baseCurrency=baseEl.value;await set('baseCurrency',baseEl.value);close();await render()});clearBtn.addEventListener('click',async()=>{if(confirm('Tüm uygulama verileri kalıcı olarak silinsin mi?')){for(const s of STORES)for(const x of await all(s))await del(s,x.id);location.reload()}})}
function modal(t,html){document.getElementById('modalTitle').textContent=t;document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}const modalEl=document.getElementById('modal');function close(){modalEl.classList.add('hidden')}function toast(x){const t=document.getElementById('toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
async function render(){await ensureRecurring();document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===S.tab));document.getElementById('main').innerHTML=S.tab==='home'?await home():S.tab==='transactions'?await transactions():S.tab==='investments'?await portfolio():await goals();bind()}
function bind(){document.getElementById('settingsBtn').onclick=settings;document.getElementById('closeModal').onclick=close;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{S.tab=b.dataset.tab;render()});document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{S.month=b.dataset.month==='-1'?prev(S.month):next(S.month);render()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='income')openTx(null,'income');if(a==='expense'||a==='newtx')openTx(null,'expense');if(a==='budget')budgetForm();if(a==='recurring')recurringForm();if(a==='buy')buyForm();if(a==='refresh')refresh();if(a==='projection'){document.querySelector('.tab[data-tab="investments"]').click();setTimeout(()=>projection(),0)}if(a==='goal')goalForm();if(a==='backup')backup();if(a==='restore')restore()});document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=async()=>openTx((await all('transactions')).find(x=>x.id===b.dataset.edit)));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Bu kayıt silinsin mi?')){await del('transactions',b.dataset.del);render()}});document.querySelectorAll('[data-sell]').forEach(b=>b.onclick=()=>sellForm(b.dataset.sell));document.querySelectorAll('[data-div]').forEach(b=>b.onclick=()=>divForm(b.dataset.div));document.querySelectorAll('[data-goaldel]').forEach(b=>b.onclick=async()=>{await del('goals',b.dataset.goaldel);render()});document.querySelectorAll('[data-goaladd]').forEach(b=>b.onclick=async()=>{const g=(await all('goals')).find(x=>x.id===b.dataset.goaladd);modal('İlerleme',`<label>Eklenecek tutar</label><input id="ga" type="number" min="0"><button class="btn" id="gas" style="margin-top:10px">Ekle</button>`);document.getElementById('gas').addEventListener('click',async()=>{g.current+=num(document.getElementById('ga').value);await put('goals',g);close();await render()})});if(S.tab==='investments')projection()}
// Expose pure test helpers only; no secrets or personal data.
export const TEST={compound:(start,monthly,annual,years)=>{const r=annual/100,rm=Math.pow(1+r,1/12)-1,n=Math.round(years*12);let fv=start*Math.pow(1+rm,n);for(let i=0;i<n;i++)fv+=monthly*Math.pow(1+rm,n-1-i);return fv},avgCost:(buys)=>{const q=buys.reduce((a,x)=>a+num(x.qty),0);return q?buys.reduce((a,x)=>a+num(x.qty)*num(x.price),0)/q:0},realized:(qty,price,cost)=>qty*(price-cost),convert:(amount,from,to,rates)=>from===to?num(amount):(num(amount)*num(rates[to])/num(rates[from])),budgetPercent:(spent,limit)=>limit>0?spent/limit*100:0,portfolio:(buys,sales,price)=>{const q=buys.reduce((a,x)=>a+num(x.qty),0),sold=sales.reduce((a,x)=>a+num(x.qty),0),avg=q?buys.reduce((a,x)=>a+num(x.qty)*num(x.price),0)/q:0,held=q-sold,value=held*num(price),realized=sales.reduce((a,x)=>a+num(x.realized),0);return{held,avg,value,unrealized:value-held*avg,realized,total:value-held*avg+realized}}};
(async()=>{try{S.db=await openDB();S.settings.baseCurrency=await get('baseCurrency','TRY');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});await render()}catch(e){document.getElementById('main').innerHTML=`<div class="card errorbox"><b>Uygulama başlatılamadı.</b><br>${esc(e.message)}</div>`}})();